query WebAdminGetRolesForUser {
  roles {
    id
    name
  }
}

query WebAdminGetOrganizationsForUser {
  organizations {
    id
    name
  }
}

mutation WebAdminCreateUser($createUserInput: CreateUserInput!) {
  createUser(createUserInput: $createUserInput) {
    id
    firstName
    lastName
    email
    role {
      id
      name
    }
  }
}

mutation WebAdminUpdateUser($updateUserInput: UpdateUserInput!) {
  updateUser(updateUserInput: $updateUserInput) {
    id
    firstName
    lastName
    email
    role {
      id
      name
    }
  }
}
