query WebAdminGetPermissionsForRole {
  permissions {
    id
    descriptiveId
    description
  }
}

query WebAdminGetOrganizationsForRole {
  organizations {
    id
    name
  }
}

mutation WebAdminCreateRole($createRoleInput: CreateRoleInput!) {
  createRole(createRoleInput: $createRoleInput) {
    id
    name
    description
    createdAt
    updatedAt
  }
}

mutation WebAdminUpdateRole($updateRoleInput: UpdateRoleInput!) {
  updateRole(updateRoleInput: $updateRoleInput) {
    id
    name
    description
    createdAt
    updatedAt
  }
}
