query AdminGetNewsletters(
  $take: Int!
  $skip: Int!
  $search: String
  $orderBy: String
  $orderDirection: String
  $schoolId: String
) {
  count: findManyNewslettersCount(search: $search, schoolId: $schoolId)
  newsletters(
    take: $take
    skip: $skip
    search: $search
    orderBy: $orderBy
    orderDirection: $orderDirection
    schoolId: $schoolId
  ) {
    id
    title
    published
    publishedAt
    school {
      id
      name
    }
    author {
      id
      name
    }
    createdAt
    updatedAt
  }
}

mutation AdminUpdateNewsletter($updateNewsletterInput: UpdateNewsletterInput!) {
  updateNewsletter(updateNewsletterInput: $updateNewsletterInput) {
    id
  }
}

mutation AdminRemoveNewsletter($removeNewsletterId: String!) {
  removeNewsletter(id: $removeNewsletterId) {
    id
  }
}
