query StudyPlanFormGetGradeMetrics {
  gradeMetrics {
    id
    name
  }
}

query StudyPlanFormDegreesBySchoolId($schoolId: String!) {
  degreesBySchoolId(schoolId: $schoolId) {
    id
    name
  }
}

mutation StudyPlanFormUpdateStudyPlanFinancialConfig($input: UpdateStudyPlanFinancialInput!) {
  updateStudyPlanFinancialConfig(input: $input) {
    id
  }
}

mutation StudyPlanFormUpdateStudyPlan($updateStudyPlanInput: UpdateStudyPlanInput!) {
  updateStudyPlan(updateStudyPlanInput: $updateStudyPlanInput) {
    id
    name
  }
}

mutation StudyPlanFormCreateStudyPlan($createStudyPlanInput: CreateStudyPlanInput!) {
  createStudyPlan(createStudyPlanInput: $createStudyPlanInput) {
    id
    name
  }
}
