query ClassGroupsFormTeachersByOrganizationId($organizationId: String!) {
  teachersByOrganizationId(organizationId: $organizationId) {
    id
    name
  }
}

query ClassGroupsFormStudyPlansBySchoolId($schoolId: String!) {
  studyPlansBySchoolId(schoolId: $schoolId) {
    id
    name
  }
}

mutation ClassGroupsFormUpdateClassGroup($updateClassGroupInput: UpdateClassGroupInput!) {
  updateClassGroup(updateClassGroupInput: $updateClassGroupInput) {
    id
    name
  }
}

mutation ClassGroupsFormCreateClassGroup($createClassGroupInput: CreateClassGroupInput!) {
  createClassGroup(createClassGroupInput: $createClassGroupInput) {
    id
    name
  }
}
