query MyAssignmentSubmission($assignmentId: String!) {
  myAssignmentSubmission(assignmentId: $assignmentId) {
    id
    assignmentId
    studentId
    fileId
    submittedAt
    file {
      id
      name
      mimeType
      size
    }
  }
}

mutation CreateSubmissionUploadUrl($input: CreateSubmissionUploadInput!) {
  createSubmissionUploadUrl(input: $input) {
    uploadUrl
    storageKey
  }
}

mutation CreateAssignmentSubmission($input: CreateAssignmentSubmissionInput!) {
  createAssignmentSubmission(input: $input) {
    id
    assignmentId
    studentId
    fileId
    submittedAt
    file {
      id
      name
      mimeType
      size
    }
  }
}

mutation DeleteAssignmentSubmission($submissionId: String!) {
  deleteAssignmentSubmission(submissionId: $submissionId)
}

mutation CreateSubmissionDownloadUrl($fileId: String!) {
  createSubmissionDownloadUrl(fileId: $fileId) {
    downloadUrl
  }
}

query StudentsForAssignment($assignmentId: String!) {
  studentsForAssignment(assignmentId: $assignmentId) {
    id
    firstName
    middleName
    fatherName
    motherName
    assignmentSubmissions {
      id
      submittedAt
      file {
        id
        name
        mimeType
        size
      }
    }
  }
}
