query CourseAttendanceClassGroupsByCourseId($courseId: String!) {
  classGroupsByCourseId(courseId: $courseId) {
    id
    name
    studyPlan {
      id
      name
    }
  }
}

query CourseAttendanceAttendanceSessions(
  $courseId: String!
  $classGroupId: String
  $skip: Int
  $take: Int
) {
  attendanceSessionsCount(courseId: $courseId, classGroupId: $classGroupId)
  attendanceSessions(
    courseId: $courseId
    classGroupId: $classGroupId
    skip: $skip
    take: $take
  ) {
    id
    date
    courseId
    classGroupId
    teacherId
    classGroup {
      id
      name
    }
    records {
      id
      studentId
      status
      comment
      student {
        id
        firstName
        middleName
        fatherName
        motherName
        classGroup {
          id
          name
        }
      }
    }
    createdAt
    updatedAt
  }
}

mutation CourseAttendanceDeleteAttendanceSession($id: String!) {
  deleteAttendanceSession(id: $id) {
    id
  }
}
