query FilesSharedWithMe($search: String) {
  filesSharedWithMe(search: $search) {
    id
    name
    mimeType
    size
    access
    updatedAt
    sharesCourses {
      course {
        id
        name
      }
    }
    sharesUsers {
      user {
        id
        name
        initials
        color
      }
    }
    sharesSchools {
      school {
        id
        name
      }
    }
    sharesClassGroups {
      classGroup {
        id
        name
      }
    }
    owner {
      id
      name
      initials
      color
    }
  }
}

query FilesOwned($search: String) {
  filesOwned(search: $search) {
    id
    name
    mimeType
    size
    access
    updatedAt
    sharesCourses {
      course {
        id
        name
      }
    }
    owner {
      id
      name
      initials
      color
    }
  }
}

mutation FilesCreateFileDownloadUrl($createFileDownloadInput: CreateFileDownloadInput!) {
  createFileDownloadUrl(createFileDownloadInput: $createFileDownloadInput) {
    downloadUrl
  }
}
