query Grade($id: String!) {
  grade(id: $id) {
    id
    title
    comments
    date
    courseId
    published
    course {
      id
      name
      studyPlan {
        id
        name
        gradeMetric {
          id
          name
          minimum
          maximum
          minimumApproval
          minimumExcellence
        }
      }
    }
    bucket {
      id
      name
      weight
    }
    period {
      id
      name
    }
    studentGrades {
      id
      student {
        id
        firstName
        fatherName
        classGroup {
          id
          name
        }
      }
      score
      comments
      updatedAt
    }
    createdAt
    updatedAt
  }
}

mutation UpdateGrade($updateGradeInput: UpdateGradeInput!) {
  updateGrade(updateGradeInput: $updateGradeInput) {
    id
    published
  }
}

mutation RemoveGrade($id: String!) {
  removeGrade(id: $id) {
    id
  }
}
