query PeriodsByYearForReport($year: Int!) {
  periodsByYear(year: $year) {
    id
    name
    shortName
    startDate
    endDate
  }
}

query GradeReport($studentId: String!, $periodId: String!) {
  gradeReport(studentId: $studentId, periodId: $periodId) {
    schoolName
    schoolLogoUrl
    periodName
    studentName
    documentId
    classGroupName
    teacherName
    studyPlanName
    level
    periods {
      id
      name
      shortName
    }
    gradesRows {
      courseId
      courseName
      periodAverages
      cumulativeAverage
    }
    overallGradesRow {
      periodAverages
      cumulativeAverage
    }
    attendanceRows {
      courseId
      courseName
      periodAttendance {
        periodId
        absent
        late
      }
    }
    habitRows {
      metricName
      value
    }
  }
}
