query GroupScheduleFormCoursesByGroupId($groupId: String!) {
  coursesByGroupId(groupId: $groupId) {
    id
    name
  }
}

mutation GroupScheduleFormUpdateGroupsSchedule($updateGroupsScheduleInput: UpdateGroupsScheduleInput!) {
  updateGroupsSchedule(updateGroupsScheduleInput: $updateGroupsScheduleInput) {
    id
  }
}

mutation GroupScheduleFormCreateGroupsSchedule($createGroupsScheduleInput: CreateGroupsScheduleInput!) {
  createGroupsSchedule(createGroupsScheduleInput: $createGroupsScheduleInput) {
    id
  }
}
