query GroupScheduleGroupsSchedulesByClassGroupId($classGroupId: String!) {
  groupsSchedulesByClassGroupId(classGroupId: $classGroupId) {
    id
    weekday
    startTime
    endTime
    location
    remote
    remoteLink
    courseId
    course {
      id
      name
      subject {
        name
      }
      teacher {
        user {
          firstName
          lastName
        }
      }
    }
  }
}

mutation GroupScheduleUpdateGroupsSchedule($updateGroupsScheduleInput: UpdateGroupsScheduleInput!) {
  updateGroupsSchedule(updateGroupsScheduleInput: $updateGroupsScheduleInput) {
    id
  }
}
