query GroupHabitsGetPeriods {
  periods {
    id
    name
    year
    startDate
    endDate
  }
}

query GroupHabitsGetHabitMetrics {
  habitMetrics {
    id
    name
    description
    active
    order
  }
}

query GroupHabitsGetHabitEvaluations($classGroupId: String!, $periodId: String!) {
  habitEvaluationsByGroup(classGroupId: $classGroupId, periodId: $periodId) {
    id
    habitMetricId
    studentEvaluations {
      id
      studentId
      value
      comments
    }
  }
}

mutation GroupHabitsSaveHabitEvaluation($saveHabitEvaluationInput: SaveHabitEvaluationInput!) {
  saveHabitEvaluation(saveHabitEvaluationInput: $saveHabitEvaluationInput) {
    id
    published
  }
}
