query ClassGroup($id: String!) {
  classGroup(id: $id) {
    id
    name
    createdAt
    updatedAt
    teacherId
    studyPlanId
    students {
      id
      name
      email
      documentId
      initials
      user {
        color
      }
    }
    courses {
      id
      name
      code
      subject {
        id
        name
      }
      teacher {
        id
        name
      }
    }
    teacher {
      id
      name
      color
      initials
      user {
        id
      }
    }
    studyPlan {
      id
      name
      degree {
        id
        name
      }
    }
  }
}
