query MessageFindMessageById($id: String!) {
  findMessageById(id: $id) {
    id
    subject
    content
    createdAt
    sender {
      id
      initials
      name
      email
      role {
        id
        name
      }
      student {
        id
      }
      teacher {
        id
      }
    }
    recipients {
      id
      user {
        id
        initials
        name
        email
        role {
          id
          name
        }
        student {
          id
        }
        teacher {
          id
        }
      }
    }
    replies {
      id
      content
      createdAt
      parentMessageId
      sender {
        id
        initials
        name
        email
      }
    }
  }
}

mutation MessageMarkAsRead($messageId: String!) {
  markMessageAsRead(messageId: $messageId) {
    id
    readAt
  }
}

mutation MessageCreateMessage($createMessageInput: CreateMessageInput!) {
  createMessage(createMessageInput: $createMessageInput) {
    id
  }
}
