query QuizzesList($organizationId: String!) {
  quizzes(organizationId: $organizationId) {
    id
    title
    details
    createdAt
    updatedAt
    course {
      id
      name
    }
    teacher {
      id
      firstName
      fatherName
    }
  }
}

query Quiz($id: String!) {
  quiz(id: $id) {
    id
    title
    details
    createdAt
    updatedAt
    course {
      id
      name
    }
    teacher {
      id
      firstName
      fatherName
    }
    questions {
      id
      question
      value
      type
      timeLimit
      options {
        id
        option
        isCorrect
      }
    }
  }
}

mutation CreateQuiz($createQuizInput: CreateQuizInput!) {
  createQuiz(createQuizInput: $createQuizInput) {
    id
    title
    details
    courseId
    teacherId
    createdAt
    updatedAt
  }
}

mutation UpdateQuiz($updateQuizInput: UpdateQuizInput!) {
  updateQuiz(updateQuizInput: $updateQuizInput) {
    id
    title
    details
    courseId
    teacherId
    createdAt
    updatedAt
  }
}

mutation RemoveQuiz($id: String!) {
  removeQuiz(id: $id) {
    id
  }
}
