query GetStudents($take: Int!, $skip: Int!, $search: String, $orderBy: String, $orderDirection: String) {
  count: findManyStudentsCount(search: $search)
  students(take: $take, skip: $skip, search: $search, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    name
    firstName
    middleName
    motherName
    birthDate
    gender
    fatherName
    documentId
    email
    classGroupId
    enrollmentStatus
    phone
    address
    classGroup {
      id
      name
    }
    user {
      id
      email
      emailVerified
      color
    }
    createdAt
    updatedAt
  }
}

mutation ResendUserInvitation($email: String!) {
  resendUserInvitation(email: $email)
}

mutation RemoveStudent($id: String!) {
  removeStudent(id: $id) {
    id
  }
}
