query StudentFinancesBalance($studentId: String!) {
  studentBalance(studentId: $studentId) {
    studentId
    totalCharges
    totalPayments
    balance
  }
}

query StudentFinancesChargesByStudent($studentId: String!) {
  chargesByStudent(studentId: $studentId) {
    id
    amount
    dueDate
    description
    chargeType
    status
  }
}

query StudentFinancesPaymentsByStudent($studentId: String!) {
  paymentsByStudent(studentId: $studentId) {
    id
    amount
    paidAt
    reference
  }
}
