query PeriodsByYear($year: Int!) {
  periodsByYear(year: $year) {
    id
    name
    startDate
    endDate
  }
}

query Student($id: String!) {
  student(id: $id) {
    id
    firstName
    fatherName
    fullName
    name
    schoolId
    enrollmentStatus
    bloodType
    allergies
    medicalNotes
    emergencyContactName
    emergencyContactPhone
    classGroup {
      id
      name
      studyPlan {
        id
        name
        gradeMetric {
          minimumApproval
          minimumExcellence
        }
      }
    }
    courses {
      id
      subject {
        name
      }
      teacher {
        id
        name
      }
    }
    parents {
      id
      firstName
      fatherName
      name
      phone
      email
      relationship
    }
    studentGrades {
      id
      score
      comments
      updatedAt
      grade {
        id
        title
        date
        comments
        published
        course {
          id
          subject {
            name
          }
        }
        bucket {
          id
          name
          weight
        }
        period {
          id
          name
        }
        createdAt
        updatedAt
      }
    }
    color
    email
    documentId
    birthDate
    initials
    gender
    address
    phone
    user {
      id
      email
      emailVerified
      color
    }
    createdAt
    updatedAt
  }
}
