query TeacherForm($id: String!) {
  teacher(id: $id) {
    id
    firstName
    middleName
    fatherName
    motherName
    documentId
    birthDate
    gender
    address
    phoneNumber
    personalEmail
    about
    teacherSince
    memberSince
    user {
      email
    }
  }
}

mutation UpdateTeacher($updateTeacherInput: UpdateTeacherInput!) {
  updateTeacher(updateTeacherInput: $updateTeacherInput) {
    id
  }
}

mutation CreateTeacher($createTeacherInput: CreateTeacherInput!) {
  createTeacher(createTeacherInput: $createTeacherInput) {
    id
  }
}
