// Generated by https://quicktype.io
import { Period } from './periods.model';
import { Student } from './students.model';
import { ClassGroup, StudyPlan } from './studyplans.model';


export interface Ranking {
  id: string;
  group: ClassGroup;
  plan: StudyPlan;
  student: Student;
  period: Period;
  grade: number;
}
