// Generated by https://quicktype.io

export interface Credit {
  id: string;
  student: string;
  documentId: string;
  year: number;
  level: string;
  period: number;
  subject: null | string;
  grade: number;
}

// Generated by https://quicktype.io

export interface GroupedCredit {
  subject: string;
  grades: Grade[];
}

export interface Grade {
  year: number;
  level: string;
  period: number;
  grade: number;
}

export interface CreditSummary {
  year: Year;
  grades: number;
}

export interface Year {
  year: number;
  level: string;
}
