// Generated by https://quicktype.io
import { Reference } from './auth/users.model';
import { EvaluationArea } from './evaluation-areas.model';
import { Period } from './periods.model';

export interface Evaluation {
  id: string;
  student: Reference;
  area: EvaluationArea;
  item: Item;
  periods: EvaluationPeriod[];
}

export interface Item {
  name: string;
  description: string;
}

export interface EvaluationPeriod {
  period: Period;
  value: string;
}

// Generated by https://quicktype.io

export interface EvaluationValue {
  area: EvaluationArea;
  evaluations: Evaluation[];
}
